### ISSUE TITLE
Ubuntu 16.04 Server with Nextcloud

### ISSUE THREAD

**Issue by Daehnie** [vpistis/OrganizeMediaFiles#7]
Hey, 

I want to sort my Media Files with your script, but I get an Traceback:
Python: 3.5.2

Traceback (most recent call last):
  File "/home/dennis/OrganizeMediaFiles/src/organize_media_files.py", line 24, in <module>
    sys.stdout = Logger()
  File "/home/dennis/OrganizeMediaFiles/src/utils.py", line 62, in __init__
    self.log = open(get_setting("LOG_FILE"), "a")
  File "/home/dennis/OrganizeMediaFiles/src/utils.py", line 20, in get_setting
    config_json = json.loads(f.read())
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 10 column 72 (char 311)

I run it with root: 'python3 organize_media_files.py'
Sorry, but I'm a noob in python!

**Comment by vpistis** [comment]
Hi @Daehnie ,

I think this error is due to the configuration file that you use:
```
File "/home/dennis/OrganizeMediaFiles/src/utils.py", line 20, in get_setting
config_json = json.loads(f.read())
```
The `config.json` file exists, have you configured it correctly with your paths? Is possible to print it, obviously masquerading your private informations?

In any case, asap I add some extra control to manage this situations,
thanx for your feedback.

**Comment by Daehnie** [comment]
Hi @vpistis 

Sure, my config seems to be correct. All path are reachable!
config.json:
{
  "LOG_FILE": "organize_media_files.log",
  "RENAME_SORTED_FILES": true,
  "REMOVE_OLD_FILES": true,
  "APPEND_ORIG_FILENAME": false,
  "DATE_FORMAT_OUTPUT": "%Y%m%d %H%M%S",

  "PROCESS_IMAGES": true,
  "IMAGE_FILENAME_SUFFIX": "Foto ",
  "IMAGES_SOURCE_PATH": "/var/nextcloud_data/Dennis/files/Photos/Dennis\ Photo\ Upload/",
  "IMAGES_DESTINATION_PATH": "/var/nextcloud_data/Dennis/files/Photos/",
  "IMAGE_FILES_EXTENSIONS": [
    ".jpg",
    ".gif",
    ".tiff"
  ],

  "PROCESS_VIDEOS": true,
  "VIDEO_FILENAME_SUFFIX": "Video ",
  "VIDEOS_SOURCE_PATH": "/var/nextcloud_data/Dennis/files/Photos/Dennis\ Photo\ Upload/",
  "VIDEOS_DESTINATION_PATH": "/var/nextcloud_data/Dennis/files/Videos/Home\ Videos/",
  "VIDEO_FILES_EXTENSIONS": [
    ".mp4",
    ".3gp",
    ".mov"
  ],

  "NEXTCLOUD": true,
  "NEXTCLOUD_PATH": "/var/www/nextcloud",
  "NEXTCLOUD_USER": "www-data"
}

**Comment by vpistis** [comment]
ok, seems the problem is the escape char in the path:
```
...
"IMAGES_SOURCE_PATH": "/var/nextcloud_data/Dennis/files/Photos/Dennis\ Photo\ Upload/",
...
```
for the script the correct path is `without` the back slash `\`:
```
...
"IMAGES_SOURCE_PATH": "/var/nextcloud_data/Dennis/files/Photos/Dennis Photo Upload/",
...
```
In the next release I make some code to prevent this.
Let me know if you have resolved.
