### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by ghost** [vpistis/OrganizeMediaFiles#8]
Getting this error when running `organize_media_files.py` with `python` on both Debian 10 and macOS 10.15

`Traceback (most recent call last):
  File "organize_media_files.py", line 22, in <module>
    from .utils import Logger, get_setting, which
ValueError: Attempted relative import in non-package`

**Comment by vpistis** [comment]
Hi,
what python version are you using?

**Comment by ghost** [comment]
Python 2.7.16

**Comment by vpistis** [comment]
The latest commit maybe resolve this bug.
Please, use python 3 instead of python 2 :)
