### ISSUE TITLE
Error on Start

### ISSUE THREAD

**Issue by madcoda9000** [vpistis/OrganizeMediaFiles#9]
1. i am logged in as root (sudo) (ubuntu 20.04)
2. all files are located at: /root/scripts/OrganizeMediaFiles/src
3. I've modified the config as suggested

`{
  "LOG_FILE": "/root/scripts/OrganizeMediaFiles/src/log.log",
  "RENAME_SORTED_FILES": true,
  "REMOVE_OLD_FILES": false,
  "APPEND_ORIG_FILENAME": false,
  "DATE_FORMAT_OUTPUT": "%Y%m%d_%H%M%S",

  "PROCESS_IMAGES": true,
  "IMAGE_FILENAME_SUFFIX": "IMG_",
  "IMAGES_SOURCE_PATH": "/mnt/Data1/Photos",
  "IMAGES_DESTINATION_PATH": "/mnt/Data1/Images",
  "IMAGE_FILES_EXTENSIONS": [
    ".jpg",
    ".gif",
    ".tiff",
    ".jpeg",
    ".png"
  ],

  "PROCESS_VIDEOS": false,
  "VIDEO_FILENAME_SUFFIX": "VID_",
  "VIDEOS_SOURCE_PATH": "/media/drivemount/user/files/FilesToSort",
  "VIDEOS_DESTINATION_PATH": "/media/drivemount/user/files/FilesSorted",
  "VIDEO_FILES_EXTENSIONS": [
    ".mp4",
    ".3gp"
  ],

  "NEXTCLOUD": false,
  "NEXTCLOUD_PATH": "/var/www/html/nextcloud",
  "NEXTCLOUD_USER": "www-data"
}`

4. when I start the script as follows:  python organize_media_files.py

I receive the following error:

`BASE DIR: /root/scripts/OrganizeMediaFiles/src
Traceback (most recent call last):
  File "organize_media_files.py", line 24, in <module>
    sys.stdout = Logger()
  File "/root/scripts/OrganizeMediaFiles/src/utils.py", line 64, in __init__
    self.log = open(get_setting("LOG_FILE"), "a")
  File "/root/scripts/OrganizeMediaFiles/src/utils.py", line 28, in get_setting
    raise Exception("Some error occurred: ", e)
Exception: ('Some error occurred: ', IOError(2, 'No such file or directory'))`

I am a bit confused as all path are existing. 

Do you have any idea?

**Comment by vpistis** [comment]
Hi,

maybe the problem can be one of:
1. the `config.json` not exists in path `/root/scripts/OrganizeMediaFiles/src`
2. the log file `/root/scripts/OrganizeMediaFiles/src/log.log` not exists, make a test creating a empty log file

Let me know if resolve.

**Comment by OCT0PUSCRIME** [comment]
@madcoda9000 Did you figure this out? I have the same issue.

**Comment by vpistis** [comment]
@OCT0PUSCRIME please check these points: https://github.com/vpistis/OrganizeMediaFiles/issues/9#issuecomment-870063601 and let me know...
